[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024