[profile.default]
src = 'src'
test = 'test'
out = 'out'
libs = ['lib', "dependencies"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 3
wrap_comments = true
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024

[soldeer]
recursive_deps = true

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
royalty-registry-solidity = { version = "1.0.0", git = "https://github.com/manifoldxyz/royalty-registry-solidity.git", rev = "e5369fc79279ce2e4c6ea2eb5914df51e89e8bd8" }
