on: [push]

name: Test

jobs:
  check:
    name: Transient Labs Sol Tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: make install

      - name: Run unit tests
        run: make compiler_test